/*
*   File: main.c
*   Description: This is the main file for the Gate control system
*   Board: Raayan Mini
*   Version: 4.0
*   Controller: STM32F4011RBT6
*   Peeiperals:I2C,UART,LCD,JQ6500 16P,SPEAKER
*   Team membetrs: Somanapalli Dinesh,Rjaesh,Ram,siraj,vijay laxmi,sravaini,bavitha
*/
#include "stm32f401rbt6.h"
#include "i2c.h"
#include "LCD.h"
#include "SysTickTimer.h"
#include "magnetic.h"
#include "SYSTEM_CONFIG.h"
#include "itoa.h"
#include "config.h"
#include "task.h"
//GLOBAL VARIABLES
int flag=0,flag13=0,flag11=0,flag12=0,time_out=0,check=0,check2=0,check11=0,check12=0;
int total=0,count=0,times=0;


int main()
{
		// Initialize the device
		device_init();
		// Configure the device for USART operation
		device_config();
		// Initialize and configure  SWITCHES
		switch_config();
		interrupt_config();
		// Initialize and configure I2C1
		KM_I2C1_Init();
		KM_I2C1_Config();
		// Initialize and configure SENSOR INTERRUPS
		SENSOR_config();
		SENSOR_intit();
		SENSEOR_INTERRRUPT_config();
		// Initialize the LCD
		km_lcd_init();
	  //DEVICE STARTING MESSAGE
	  starting_message();

	
	
  
	while(1)
	{
    // read rtc and display time
		rtc_read_1sec();
		//check sensor data and dispaly message
		task2_check_sensor();
		//check11 is set when the user wants to configure the time
		//call time_config function with check11 as argument
		//reset check11 to 0
		if(check11==1)
		{
		time_config(check11);
		check11=0;
		}
		//check12 is set when the user wants to configure the volume
		//call volume_config function with check12 as argument
		//reset check12 to 0
		if(check12==1)
		{
		volume_config(check12);
		check12=0;
		}
		//flag13 is set when the user wants to reset the device
		if(flag13==1)
		{
		flag13=0;                                     //reset flag13 to 0
		device_reset();                               //call device_reset function
		}
		//enable interrupt for EXTI line 0
		EXTI_IMR |=0X01;	
		//total_count();
  }
	}


	
/**
 * @brief Interrupt handler for EXTI line 0
 * This function is the interrupt handler for EXTI line 0. When the interrupt
 * is generated, it resets the count of the timer, sets flag11 to 1, clears the
 * interrupt flag in EXTI_PR register and disables the interrupt by writing 0
 * to the corresponding bit in EXTI_IMR register.
 */
	void EXTI0_IRQHandler()
	{

		// Reset the count of the timer
		count = 0;
		// Set flag11 to indicate an event has occurred
		flag11 = 1;
		// Clear the interrupt flag in EXTI_PR register for line 0
		EXTI_PR |= (0x01 << 0);
		// Reset the timeout counter
		time_out = 0;
		// Disable the interrupt for EXTI line 0
		EXTI_IMR &= ~(0x01);
		
	}
/**
 * @brief This function is used to handle the interrupts generated by the two
 *        switches connected to PC8 and PC9. When the interrupt is generated
 *        it checks the state of the switches and sets the flag and check
 *        variables accordingly.
 * @note  The interrupts are falling edge triggered.
 * @note  The interrupt is cleared by writing 1 to the corresponding bit in
 *        EXTI_PR register.
 */

void EXTI9_5_IRQHandler(void)
  {
   {
        // Check if the button connected to PC8 is pressed
        if(!(GPIOC_IDR & (0x01 << 8)))
        {
            check11 = 1; // Set check11 to 1 to trigger time configuration
        }
        // Check if the button connected to PC9 is pressed
        if(!(GPIOC_IDR & (0x01 << 9)))
        {
            check12 = 1; // Set check12 to 1 to trigger volume configuration
        }
    }
	
		EXTI_PR|=(0X03<<8);//clear the interrpt pr
	}
/**
 * @brief  This function is used to handle the interrupts generated by the two
 *         switches connected to PC10 and PC13. When the interrupt is generated
 *         it checks the state of the switches and sets the flag and check
 *         variables accordingly.
 * @note   The interrupts are falling edge triggered.
 * @note   The interrupt is cleared by writing 1 to the corresponding bit in
 *         EXTI_PR register.
 */
void EXTI15_10_IRQHandler(void)
	{
		if((EXTI_PR&(0X01<<10)))//checking 10th is on or off
		{
		 flag13=1;
		 EXTI_PR|=(0X01<<10);//clear the interrpt pr
		}
		else if((EXTI_PR&(0X01<<13)))
		{
			// The interrupt is generated by the switch connected to PC13
			// Set flag12 to 1
			flag12=1;
			// Increment the times variable
			// If the times variable reaches 150, reset it to 0 and increment
			// the count variable

			if(times==150)
			{
				times=0;
				count++;

			}
			times++;

		EXTI_PR|=(0X01<<13);//clear the interrpt pr
		}
		
  }